-- NOTE: naming_conventions table already created in 20260308000000_naming_conventions.sql
-- This migration is a no-op to prevent duplicate table creation errors.
-- All table structure, RLS policies, and triggers exist in the original migration.
